---
title: "brain-size-neuron-plot"
author: "Charmi"
date: "10/5/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(magrittr)
library(gdata)
library(ggrepel)

```

<center><h1> Goals </h1>
<br>
<i>Load data </i> </center>

```{r}
hh <- read.csv("../data/cleaned/herculano-houtzel-all.csv")
```
<center><h2> Plots </h2> </center>
<br>
<br>
<center> <i> Equation of the regression line for plot of 'Brain mass by number of neurons' </i></center>


```{r, echo=FALSE}

#define reg_func for abline

reg_func <- lm(log(N_neurons) ~ log(Mass_g), data = hh)
coeff = coefficients(reg_func)
slp = round(coeff[2],1)
inp = round(coeff[1],1)

#equation of the regression line

eq = paste0("y = ", slp, "*x + ", inp)
```

<center> <h3> Plot of Brain mass by Number of Neurons </h3></center>

```{r plot, echo = FALSE, fig.align='center'}
x <- log(hh$Mass_g)
y <- log(hh$N_neurons)
#plot the data
hh %>%
    ggplot() +
    aes(x = x, y = y) +
    labs(x = "Structure mass (g)", y = "Number of Neurons") +
    geom_point(col = ifelse((x > 2*IQR(x)| y> 7.5*IQR(y)), "red", "black")) +
    geom_abline(intercept = inp, slope = slp, color = "blue", size = 0.5) +
    geom_text_repel(aes(label = ifelse((x > 2*IQR(x)| y> 7.5*IQR(y)), paste0(Species), "")), col = "red")
```

<center> <i> equation of the regression line plotted above is: </i> </center>

```{r regression_line, echo=FALSE}

centerText(eq)

```


<center> <h3> Labelling all Homosapiens in the Graph </h3> </center>

```{r plot_graph, echo = FALSE, fig.align= "center"}
#plot same data with only 'homosapiens' labelled

hh %>%
    ggplot() +
    aes(x = x, y = y) +
    labs(x = "Structure mass (g)", y = "Number of Neurons") +
    geom_point(col = ifelse(hh$Species == "Homosapiens", "red", "black")) +
    geom_abline(intercept = inp, slope = slp, color = "blue", size = 0.5) +
    geom_text_repel(aes(label = ifelse(hh$Species == "Homosapiens", paste0(Species), "")), col = "red")

# dataplot + stat_smooth(method="lm", se=FALSE) --> smooth line

#Another way of plotting graph

# lm_func = lm(log(N_neurons) ~ log(Mass_g), data = hh)
# plot(log(N_neurons) ~ log(Mass_g), data=hh, main="Neurons vs mass") + abline(lm_func, col="red")

```




