---
title: "hh-paper-plots"
author: "Charmi Mehta"
date: "1/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(magrittr)
library(gdata)
library(ggrepel)
library(dplyr)
```

<center><h1> Goals </h1>
<br>
<i>Load data and separate into different brain areas</i> </center>

```{r}
#load data

hh <- read.csv("../data/cleaned/herculano-houtzel-all.csv")

#Separating different brain areas

cerebellum_dat <- hh[which(hh$Brain_area == 'cerebellum'),]
cerebral_ctx_dat <- hh[which(hh$Brain_area == 'cerebral_ctx'), ]
olf_bulb_dat <- hh[which(hh$Brain_area == 'olf_bulb'), ]
whole_brain_dat <- hh[which(hh$Brain_area == 'whole_brain'), ]
rest_of_brain_dat <- hh[which(hh$Brain_area == 'rest_of_brain'), ]

# cerebellum_dat
cerebral_ctx_dat
# olf_bulb_dat
# whole_brain_dat
# rest_of_brain_dat

```

<center><h2> Plots </h2> </center>
<br>
<br>
<center> <i> Plot without naked mole rat, but with house mouse </i></center>

**A better fit to the same data points is found when the mouse is included in the analysis (exponent, 1.699 ± 0.096, r2 = 0.975, p < 0.0001), and still excludes the naked mole-rat.**

```{r plot1, echo=FALSE}

glires_ctx <- cerebral_ctx_dat[which(cerebral_ctx_dat$Order == 'Glires'), ]
glires_ctx <- glires_ctx[glires_ctx$Species != "Heterocephalusglaber", ]
glires_ctx

#define x and y axis variables

neur_glires_a <- log(glires_ctx$N_neurons)
wt_glires_a <- log(glires_ctx$Mass_g)

#Defining Q1, Q3, upperlimit, and lowerlimit of x-axis (Mass(g))

Quart_for_wt <- quantile(wt_glires_a)

Q3_for_wt <- Quart_for_wt[4]
Q1_for_wt <- Quart_for_wt[2]

upperlimit_for_wt <- Q3_for_wt + 1.5*IQR(wt_glires_a)
lowerlimit_for_wt <- Q1_for_wt - 1.5*IQR(wt_glires_a)

#Defining Q1, Q3, upperlimit, and lowerlimit of x-axis (Mass(g))

Quart_for_neur <- quantile(neur_glires_a)

Q3_for_neur <- Quart_for_neur[4]
Q1_for_neur <- Quart_for_neur[2]

upperlimit_for_neur <- Q3_for_neur + 1.5*IQR(neur_glires_a)
lowerlimit_for_neur <- Q1_for_neur - 1.5*IQR(neur_glires_a)

#Plot the data with outliers

glires_ctx %>%
    ggplot() +
    aes(x = neur_glires_a, y = wt_glires_a) +
    labs(x = "Log number of neurons", y = "Log structure mass (g)") +
    geom_point(col = ifelse((wt_glires_a > upperlimit_for_wt | 
                               neur_glires_a > upperlimit_for_neur | 
                               wt_glires_a < lowerlimit_for_wt | 
                               neur_glires_a < lowerlimit_for_neur), "red", "black")) +
    geom_smooth(method = "lm" ,color = "blue", size = 0.5) +
    geom_text_repel(aes(label = ifelse((wt_glires_a > upperlimit_for_wt | 
                                          neur_glires_a > upperlimit_for_neur | 
                                          wt_glires_a < lowerlimit_for_wt | 
                                          neur_glires_a < lowerlimit_for_neur), 
                                       paste0(Species), "")), col = "red")

```


``` {r plot2, echo=FALSE}



glires_ctx %>%
    ggplot() +
    aes(x = neur_glires_a, y = wt_glires_a) +
    labs(x = "Log number of neurons", y = "Log structure mass (g)") +
    geom_point(col = ifelse((wt_glires_a > upperlimit_for_wt | 
                               neur_glires_a > upperlimit_for_neur | 
                               wt_glires_a < lowerlimit_for_wt | 
                               neur_glires_a < lowerlimit_for_neur), "red", "black")) +
    geom_smooth(method = "lm" ,color = "blue", size = 0.5) +
    geom_text_repel(aes(label = ifelse((wt_glires_a > upperlimit_for_wt | 
                                          neur_glires_a > upperlimit_for_neur | 
                                          wt_glires_a < lowerlimit_for_wt | 
                                          neur_glires_a < lowerlimit_for_neur), 
                                       paste0(Species), "")), col = "red")

```











